version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./movielens:/movielens
      - mongodb_data:/data/db  

  flask_api:
    build:
      context: ./mongodb_dw
      dockerfile: Dockerfile  
    container_name: flask_api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend 
    container_name: frontend
    ports:
      - "8000:8000"
    depends_on:
      - flask_api
      - supabase_api
      - neo4j_api

  supabase_api:
    image: nginx 
    dockerfile: Dockerfile  
    container_name: supabase_api
    ports:
      - "5050:5050"

# 4) Actual Neo4j database (the official DB image)
  neo4j:
    image: neo4j:5.5
    container_name: neo4j
    environment:
      # set user/pass here or use NEO4J_AUTH
      NEO4J_AUTH: "neo4j/password"
    ports:
      - "7474:7474"  # Browser
      - "7687:7687"  # Bolt port for driver

  # ─────────────────────────────────────────────────────────
  # 5) Your Neo4j-based Flask API (build from your neo4j folder)
  neo4j_api:
    build:
      context: ./neo4j
      dockerfile: Dockerfile  # the Dockerfile in the neo4j folder
    container_name: neo4j_api
    ports:
      - "6060:6060"  # Expose port 6060 for Flask
    depends_on:
      - neo4j

volumes:
  mongodb_data:
